[customizations.installer.kickstart]
contents = """

clearpart --all --initlabel --disklabel=gpt
reqpart --add-boot
part / --grow --fstype ext4

%post
bootc switch --mutate-in-place --transport registry oci.heliumos.org/heliumos/bootc:10
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Timezone", 
  "org.fedoraproject.Anaconda.Modules.Localization" 
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
